---
- hosts: "{{ lookup('env', 'HOST') }}"
  vars:
    - ansible_become_pass: "{{ lookup('env', 'SUDO_PASSWORD') }}"

  remote_user: buddy

  tasks: 
 
  - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
    apt:
      update_cache: yes
      cache_valid_time: 3600
    become: yes
    become_method: sudo
  
  - name: Update all packages to the latest version
    apt:
      upgrade: yes
    become: yes
    become_method: sudo
